apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-vault-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kms-vault-operator
  template:
    metadata:
      labels:
        name: kms-vault-operator
    {{- if (default .Values.global.podAnnotations .Values.podAnnotations) }}
      annotations: {{ toYaml (default .Values.global.podAnnotations .Values.podAnnotations) | nindent 8 }}
    {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: kms-vault-operator
        image: patoarvizu/kms-vault-operator:{{ default .Values.global.imageVersion .Values.imageVersion }}
        imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.imagePullPolicy }}
        command:
        - /manager
        args:
        - --enable-leader-election
        - --vault-authentication-method={{ .Values.vaultAuthenticationMethod }}
        - --sync-period-seconds={{ .Values.syncPeriodSeconds }}
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.watchNamespace | quote }}
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
        - name: VAULT_ADDR
          value: {{ .Values.vault.address }}
        {{- toYaml .Values.authMethodVariables | nindent 8 }}
        {{- if .Values.aws.iamCredentialsSecrets }}
        {{- toYaml .Values.aws.iamCredentialsSecrets | nindent 8 }}
        {{- end }}
        {{- if not .Values.tls.enable }}
        - name: VAULT_SKIP_VERIFY
          value: "true"
        {{- else }}
        - name: VAULT_CAPATH
          value: {{ .Values.tls.mountPath }}/{{ .Values.tls.certFileName }}
        volumeMounts:
        - name: tls
          mountPath: {{ .Values.tls.mountPath }}
        {{- end }}
        {{- if (default .Values.global.resources .Values.resources) }}
        resources: {{ toYaml (default .Values.global.resources .Values.resources) | nindent 10 }}
        {{- end }}
      {{- if .Values.tls.enable }}
      volumes:
      - name: tls
        secret:
          secretName: {{ .Values.tls.secretName }}
      {{- end }}